### ISSUE TITLE
API docker instance failing after attempting uplift to v1.1.2

### ISSUE THREAD

**Issue by beastarman74** [snypy/snypy-backend#85]
I tried uplifting to the latest version but on doing so I found that the api instance was stopping very quickly after running docker-compose up. 

[2022-05-13 22:17:48 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/environ/environ.py", line 367, in get_value
    value = self.ENVIRON[var]
  File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CSRF_TRUSTED_ORIGINS' 

Full error log in attached text file due to length.
[error.txt](https://github.com/snypy/snypy-backend/files/8691610/error.txt)

I tried going to v1.1.1 but found it is now doing the same. I had to rollback to 1.1.0.

**Comment by nezhar** [comment]
Try setting up the CSRF_TRUSTED_ORIGINS in the `docker-compose.override.yml` for the api service. This Variabel has been introduced with 1.1.1 https://github.com/snypy/snypy-docker/commit/8f500214d380127e6ebd614f3ba305ac2d8bcf55 as it upgrades internally to Django 4.0 - https://docs.djangoproject.com/en/4.0/releases/4.0/#csrf

**Comment by beastarman74** [comment]
Yes that sorted it.
I must sincerely apologize for wasting your time with this, I neglected to check the docker-compose.override.yml file for changes. I notice this entry was in it 2 days ago. I will check going forwards.
Thanks, Paul.

**Comment by nezhar** [comment]
Don''t worry. Such issues help us create better documentation for future users and releases :slightly_smiling_face: :muscle:
